# Generated by Django 3.0.14 on 2022-06-11 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequeimport',
            name='importDate',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='ChequeImportLine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chequeImportLineCode', models.CharField(max_length=100)),
                ('chequeImportLineDate', models.DateTimeField()),
                ('chequeImportLineStatus', models.CharField(max_length=50)),
                ('chequeImportId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cs.ChequeImport')),
            ],
            options={
                'db_table': 'tblChequeSanteImportLine',
            },
        ),
    ]
