# Generated by Django 3.2.25 on 2024-05-15 11:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_last_login_on_interactive_user'),
        ('cs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChequeUpdatedHistory',
            fields=[
                ('idChequeUpdated', models.AutoField(db_column='ChequeUpdatedID', primary_key=True, serialize=False)),
                ('updated_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Current Updated Date')),
                ('description', models.TextField(max_length=200)),
                ('chequeImportLine', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cs.chequeimportline')),
                ('user', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.DO_NOTHING, to='core.interactiveuser')),
            ],
            options={
                'db_table': 'cheque_updated_history',
            },
        ),
    ]
