# Generated by Django 3.0.14 on 2022-06-11 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0002_auto_20220611_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chequeimport',
            old_name='id',
            new_name='idChequeImport',
        ),
        migrations.RenameField(
            model_name='chequeimportline',
            old_name='id',
            new_name='idChequeImportLine',
        ),
    ]
